[package]
name = "kaizen-zed"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/kzn-tools/zed"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
