id = "kaizen"
name = "Kaizen"
version = "0.1.0"
schema_version = 1
authors = ["mpiton <contact@mpiton.dev>"]
description = "Ultra-fast JavaScript/TypeScript static analyzer"
repository = "https://github.com/kzn-tools/zed"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.kaizen-lsp]
name = "Kaizen"
languages = ["JavaScript", "TypeScript"]
